name: ModifiedBosses
version: '${project.version}'
main: net.reworlds.modifiedbosses.ModifiedBosses
api-version: '1.20'
author: 'Statuxia'
depend:
  [ProtocolLib, UltimateAdvancementAPI]

commands:
  rp:
    description: "Установить ресурспак сервера"
  bestiary:
    description: "Бестиарий боссов"
  bossDamage:
    description: ""