name: ModifiedBosses
version: '${project.version}'
main: net.reworlds.modifiedbosses.ModifiedBosses
api-version: '1.20'

commands:
  charms:
    description: "get charms"
  givereward:
    description: "gives reward"